vs2022/starwars-game/WebApplication4/Models/DefaultDbContext.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApplication4.Models
{
    public class DefaultDbContext : DbContext
    {
        public DefaultDbContext(DbContextOptions options) : base(options)
        {
        }

        protected DefaultDbContext()
        {
        }

        /// <summary>
        /// C'est une LISTE ! et elle sera connectée à une table en bdd
        /// </summary>
        public DbSet<Personne> Personnes { get; set; }

        //public static implicit operator ControllerContext(DefaultDbContext v)
        //{
            //throw new NotImplementedException();
        //}
    }
}

vs2022/starwars-game/WebApplication4/Models/ErrorViewModel.cs
namespace WebApplication4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

vs2022/starwars-game/WebApplication4/Models/Personne.cs
namespace WebApplication4.Models
{
    public class Personne
    {
        public int Id { get; set; }

        public string Prenom { get; set; }
    }
}

vs2022/starwars-game/WebApplication4/Models/PersonneAddViewModel.cs
namespace WebApplication4.Models
{
    public class PersonneAddViewModel
    {
        public Personne? LaPersonne { get; set; }
    }
}

vs2022/starwars-game/WebApplication4/Controllers/EditionController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication4.Controllers
{
    public class EditionController : Controller
    {
        public IActionResult Edit()
        {
            return View();
        }
    }
}

vs2022/starwars-game/WebApplication4/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

vs2022/starwars-game/WebApplication4/Controllers/PersonneController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class PersonneController : Controller
    {
        private readonly DefaultDbContext context;
        // Parce que j'ai ajouté la ligne :
        // builder.Services.AddDbContext<DefaultDbContext>();
        public PersonneController(DefaultDbContext context)
        {
            this.context = context;
        }
        public IActionResult List()
        {
            //List<Personne> list = new()
            //{
            //   new() { Id= 1, Prenom = "Isidor" },
            //  new() { Id= 2, Prenom = "Batman" }
            //};
            var query = from item in this.context.Personnes
                        select item;

            var modelAEnvoyerALaView = query.ToList();

            return View(modelAEnvoyerALaView);
        }

        public IActionResult EditPersonne()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(PersonneAddViewModel item)
        {
            string value = this.Request.Form["chtulu"];

            this.context.Personnes.Add(item.LaPersonne);
            //this.context.Personnes.Add(new Personne());
            this.context.SaveChanges();
            return RedirectToAction("List");
        }
    }

    public class Pieuvre
    {
        public string Chtulu { get; set; }
    }

}

vs2022/starwars-game/WebApplication4/Views/Edition/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Edition</h1>

vs2022/starwars-game/WebApplication4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

vs2022/starwars-game/WebApplication4/Views/Personne/Add.cshtml
<form asp-action="Add" asp-controller="Personne" method="post">
    <input type="text" name="chtulu" />
    <input type="text" name="LaPersonne.Prenom" />
    <button type="submit">Ajouter</button>
</form>

vs2022/starwars-game/WebApplication4/Views/Personne/EditPersonne.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1 style="text-align: center; color: #FF0000;">Edition des personnes</h1>
<p style="color: blue; text-align: justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin euismod nunc id lorem aliquet porttitor. Nulla vitae magna ex. Phasellus sit amet euismod risus, in tempor nisi. Fusce blandit finibus turpis, a bibendum erat blandit non. Suspendisse et fermentum sem. Morbi euismod risus eu ipsum interdum, vel cursus libero condimentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse id ex ac arcu auctor placerat. Mauris vitae turpis vitae ligula malesuada suscipit. Phasellus urna risus, hendrerit a dolor et, vestibulum sagittis leo. Praesent vestibulum nunc ac ante porta sollicitudin. Nunc finibus aliquet tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin quis ante ac mi accumsan fringilla eu ut nulla.</p>
<p style="color: green; text-align: justify;">Quisque convallis nibh consequat, elementum ante et, tempor sem. In iaculis pharetra ante. In varius rutrum risus id bibendum. Proin lacinia quis elit sed ornare. Proin sed sem nulla. Suspendisse elementum orci tellus, viverra auctor quam efficitur et. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus efficitur quam in ultricies rhoncus. Phasellus in lectus et nisl venenatis maximus.</p>

vs2022/starwars-game/WebApplication4/Views/Personne/List.cshtml
@model List<Personne>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    
}


<h1> La liste des personnes</h1>
@if(Model.Count > 0)
{
    <select>
        @foreach(var item in this.Model)
        {
            <option>@(item.Prenom.ToLower())</option>
        }
    </select>
}
else
{
    <i>Aucune personne présence dans la liste</i>
}

vs2022/starwars-game/WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>