vs2022/starwars-game/starwars.game.Web.UI/Models/DefaultDbContext.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace starwars.game.Web.UI.Models
{
    public class DefaultDbContext : DbContext
    {
        public DefaultDbContext(DbContextOptions options) : base(options)
        {
        }

        protected DefaultDbContext()
        {
        }

        /// <summary>
        /// C'est une LISTE ! et elle sera connectée à une table en bdd
        /// </summary>
        public DbSet<Game> Games { get; set; }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/ErrorViewModel.cs
namespace starwars.game.Web.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/Game.cs
namespace starwars.game.Web.UI.Models
{
    public class Game
    {
        public int Id { get; set; }

        public string Pseudo { get; set; }

        public String DateGame { get; set; }

        //public String DateCheckP { get; set; }

        //public int PDV { get; set; }

    }
}

vs2022/starwars-game/starwars.game.Web.UI/Models/GameAddViewModel.cs
namespace starwars.game.Web.UI.Models
{
    public class GameAddViewModel
    {
        public Game? LaGame { get; set; }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using starwars.game.Web.UI.Models;
using System;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace starwars.game.Web.UI.Controllers
{
    public class GameController : Controller
    {
        private readonly DefaultDbContext context;
        public GameController(DefaultDbContext context)
        {
            this.context = context;
        }
        public IActionResult List()
        {
            var query = from item in this.context.Games
                        select item;

                var modelAEnvoyerALaView = query.ToList();

                return View(modelAEnvoyerALaView);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(GameAddViewModel item)
        {

            this.context.Games.Add(item.LaGame);
            //this.context.Personnes.Add(new Personne());
            this.context.SaveChanges();
            return RedirectToAction("List");
        }
    }

}

vs2022/starwars-game/starwars.game.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using starwars.game.Web.UI.Models;
using System.Diagnostics;

namespace starwars.game.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

vs2022/starwars-game/starwars.game.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

vs2022/starwars-game/starwars.game.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - starwars.game.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/starwars.game.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">starwars.game.Web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="game" asp-action="List">Liste des games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - starwars.game.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

vs2022/starwars-game/starwars.game.Web.UI/Views/game/Add.cshtml
<form asp-action="add" asp-controller="Game" method="post">
    <label>Pseudo</label>
    <input type="text" name="SauvegardePlayer" />
    <button type="submit">Sauvegarder</button>
</form>

vs2022/starwars-game/starwars.game.Web.UI/Views/game/List.cshtml
@model List<Game>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>La liste des games</h1>
@if (Model.Count > 0)
{
    <table style="border: 1px dotted black;">
        @foreach(var item in this.Model)
        {
            <tr>
                <td style="border: 1px dotted black;">@(item.Id)</td>
                <td style="border: 1px dotted black;">@(item.DateGame)</td>
            </tr>
        }
    </table>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="game" asp-action="Add">Nouvelle sauvegarde</a>
    </li>
}
else
{
    <i>Aucune partie commencée</i>
}